# Generated by Django 4.2.5 on 2024-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_course_student_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=100)),
                ('exp_month', models.CharField(max_length=100)),
                ('exp_year', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
    ]
