# Generated by Django 4.2.5 on 2024-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.IntegerField(default=1000000),
        ),
    ]
