# Generated by Django 4.2.5 on 2024-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bank_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(default='', upload_to='images/branch/'),
        ),
    ]
