# Generated by Django 4.2.5 on 2024-04-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='staff_id',
        ),
    ]
