# Generated by Django 4.2.5 on 2024-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_timetable_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='period1',
        ),
        migrations.AddField(
            model_name='timetable',
            name='period2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='period3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='period4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='period5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
