# Generated by Django 4.2.5 on 2024-04-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_time_timetable_period1_timetable_period2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_id',
        ),
    ]
