# Generated by Django 4.2.5 on 2024-04-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
