# Generated by Django 4.2.5 on 2024-04-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('notes_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.FileField(default='', upload_to='images/notes/')),
                ('date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
