# Generated by Django 4.2.5 on 2024-04-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
    ]
