# Generated by Django 4.2.5 on 2024-04-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_staff_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='exp_month',
            new_name='exp_date',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='exp_year',
        ),
    ]
