# Generated by Django 4.2.5 on 2024-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_mock_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
    ]
