# Generated by Django 4.2.5 on 2024-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='reply',
            field=models.TextField(default=''),
        ),
    ]
