# Generated by Django 4.2.5 on 2024-04-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_enquiry_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='reply',
        ),
    ]
