# Generated by Django 4.2.5 on 2024-04-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_enquiry_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
