# Generated by Django 4.2.5 on 2024-04-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_fee_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('instalment_no', models.IntegerField()),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.batch')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'db_table': 'student_fee_payment',
            },
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
