# Generated by Django 4.2.5 on 2024-04-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_student_fee_payment_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_fee_payment',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='student_fee_payment',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='student_fee_payment',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_fee_payment',
            name='instalment_no',
            field=models.IntegerField(default=1),
        ),
    ]
