# Generated by Django 4.2.5 on 2024-04-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_amount_student_fee_payment_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fee_payment',
            name='course_id',
        ),
    ]
