# Generated by Django 4.2.5 on 2024-04-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock_question',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
